SET-757 Check for java and maven executable or not before starting the job.
jboss-set/harmonia pull request #127
Opened 2024-04-29 17:16 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/SET-757

2024-04-30 07:50 UTC, RanabirChakraborty commented
@rpelisse can you please review it.

2024-04-30 08:00 UTC, rpelisse requested changes
See comment in the code.

2024-04-30 08:00 UTC, rpelisse commented on eap-job/base.sh
> +    echo "No Maven Home defined or path is wrong. Please check."
I think it's a bit misleading. I would do two separate if stmt. First one checking if the file exists with a proprer "file does not exists" msg and another one checking if the (now-existing-for-sure) file is executable, with a proper "command was found, but is not executable".
I would exit if any of those tests fail. (adding a readonly variable holding the exit code specific to each type of error).

2024-04-30 08:10 UTC, RanabirChakraborty commented on eap-job/base.sh
> +    echo "No Maven Home defined or path is wrong. Please check."
Those are being done [here](https://github.com/jboss-set/harmonia/blob/main/eap-job/base.sh#L50-L53), after all the MAVEN_HOME path setup is done when it's exporting the path after that checking if it's executable or not.

2024-05-01 06:05 UTC, RanabirChakraborty commented
@rpelisse I have done the required changes, please review once.

2024-05-03 07:51 UTC, rpelisse requested changes
See comment in code

2024-05-03 07:51 UTC, rpelisse commented on eap-job/base.sh
> +    echo "MAVEN_HOME is set and file is executable."
I appreciate the good intention, but I think this will pollute the log. It's going to be OK 99,999%. I suggest we just keep the else stmt:
```

if [ ! -x ${MAVEN_HOME}/bin/mvn" ]; then
  echo "MAVEN_HOME is defined but the file is not executable."
  exit 5
fi
```
I also suggest to use 5 instead of 1 for the exit value. Looking at the other exit stmt in eap-job/ 5 is the next available error code and this way, this particular failure will have its own code.

2024-05-03 07:51 UTC, rpelisse commented on eap-job/base.sh
> +    export PATH="${JAVA_HOME}/bin:${PATH}"
Same as below applies here.

2024-05-03 08:07 UTC, rpelisse approved these changes
LGTM! Let me know when the test run has successfully finished and I'll merge.

2024-05-03 08:25 UTC, rpelisse approved these changes

2024-05-03 12:48 UTC, RanabirChakraborty commented
@rpelisse when java is not executable log - https://olympus-host.lab.eng.brq2.redhat.com/jenkins/view/wildfly/job/wildfly-test-build/18/console
and a successful one - https://olympus-host.lab.eng.brq2.redhat.com/jenkins/view/wildfly/job/wildfly-test-build/20/console

2024-05-07 11:02 UTC, merged