SET-769 CCI having broken EAP6.4 jobs
jboss-set/harmonia pull request #131
Opened 2024-06-07 19:01 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/SET-769

2024-06-07 19:04 UTC, RanabirChakraborty commented
@spyrkob Ingo please review this PR, below are the CCI job results.
eap-6.4.x-build #88 and eap-6.4.x-ranabir-testsuite #14

2024-06-10 05:36 UTC, iweiss commented
I see you removed tests for `IS_CCI`, does this mean the script now works on both CCI and Olympus without issues?

2024-06-10 07:40 UTC, spyrkob commented
IIRC those were needed because in Olympus we mount the build workspace rather than zip/unizp and transfering via Jenkins mechanism.

2024-06-11 13:05 UTC, RanabirChakraborty commented
PR is modified and working fine now check eap-6.4.x-build 95

2024-06-11 13:29 UTC, spyrkob commented on eap-job-64.sh
> -readonly MAVEN_SETTINGS_XML=${MAVEN_SETTINGS_XML-'/home/master/settings.xml'}
Aren't we using settings.xml on Olympus to provide some proxy caching?

2024-06-11 13:29 UTC, spyrkob commented on eap-job-64.sh
> +    export MVN_ARGS="-DsomeNoneEmptyValue"
What is the default value in integration-tests.sh? Do you mean https://github.com/jbossas/jboss-eap/blob/6.4.x/integration-tests.sh#L33 ?

2024-06-12 05:01 UTC, RanabirChakraborty commented on eap-job-64.sh
> +    export MVN_ARGS="-DsomeNoneEmptyValue"
Yes, but ultimately MVN_ARGS will be overriden by -DsomeNoneEmptyValue only, while running the testsuite in CCI.

2024-06-12 05:14 UTC, RanabirChakraborty commented on eap-job-64.sh
> -readonly MAVEN_SETTINGS_XML=${MAVEN_SETTINGS_XML-'/home/master/settings.xml'}
I checked inside `base.sh` script there was no mention of `MAVEN_SETTINGS_XML` param, We are passing this from the Jenkins job itself for CCI as well as in Olympus.

2024-06-12 08:02 UTC, spyrkob commented on eap-job-64.sh
> -readonly MAVEN_SETTINGS_XML=${MAVEN_SETTINGS_XML-'/home/master/settings.xml'}
In EAP7 jobs it's set in https://github.com/spyrkob/harmonia/blob/olympus/eap-job/olympus.sh#L10

2024-06-12 11:03 UTC, spyrkob commented on eap-job-64.sh
> -readonly MAVEN_SETTINGS_XML=${MAVEN_SETTINGS_XML-'/home/master/settings.xml'}
actually we don't have /home/master so that must be a leftover from thunder...

2024-06-12 11:03 UTC, spyrkob approved these changes

2024-06-17 12:51 UTC, rpelisse commented on eap-job-64.sh
> +    dist_folder="dist/target"
Maybe a readonly envVar could be a nicer approach:
```
readonly DIST_FOLDER=${DIST_FOLDER:-'dist/target'}
```
So, for job requiring `build` instead of `dist`, we can just add `DIST_FOLDER='build/target'` to the job. (just a thought)

2024-06-17 13:02 UTC, rpelisse commented on eap-job-64.sh
> +  if [ "$maven_version" = "3.2.5" ]; then
```
  if [ "${maven_version}" = "3.2.5" ]; then
 ```

2024-06-20 10:14 UTC, rpelisse commented on eap-job-64.sh
> +    echo "${DIST_FOLDER}"
I would remove the echo as you can see this value when you run the script with -x. If you prefer to keep it, then add if [ -z ${DEBUG} ]; around it and prefix the value:
`
echo DIST_FOLDER:${DIST_FOLDER}`

2024-06-20 10:14 UTC, rpelisse commented on eap-job-64.sh
> +  bash -x ./build.sh ${MAVEN_VERBOSE}  "${FAIL_AT_THE_END}" ${MAVEN_SETTINGS_XML_OPTION} -B ${BUILD_OPTS} ${@}
You should use the debug function here too

2024-06-21 05:42 UTC, rpelisse approved these changes

2024-06-21 05:42 UTC, rpelisse commented on eap-job-64.sh
> +    readonly DIST_FOLDER=${DIST_FOLDER:-'dist/target'}
I should have noticed that on the first pass, sorry.
This does not need to be a function, especially as its just wrapping the declaration of a constant. Simply add this line to the other vars (around line 97 of this script).

2024-06-21 05:42 UTC, rpelisse commented on eap-job-64.sh
> +
We can remove this extra empty line.

2024-06-21 05:42 UTC, rpelisse commented on eap-job-64.sh
> +  maven_version=$(mvn -v | awk '/Apache Maven/ {print $3}')
as maven_version is never going to change value,  it should be a constant so:
`
readonly MAVEN_VERSION=...
`

2024-06-21 05:42 UTC, rpelisse commented on eap-job-64.sh
> +  if [ "${maven_version}" ! = "3.2.5" ]; then
I think the space between ! and = is going to break things... Did you try the script?

2024-06-21 05:42 UTC, rpelisse commented on eap-job-64.sh
>    if [ -n "${IS_CCI}" ]; then
We can remove this extra empty line

2024-06-21 05:42 UTC, rpelisse commented on eap-job-64.sh
> +  if [ "${maven_version}" ! = "3.2.5" ]; then
Same remark as above, I'm not sure about the space between ! and =

Also, as those 5 lines entirely duplicates the one above, what about moving the if stmt inside the maven_setup function? So in both occurence, we just called maven_setup... This will reduce code duplication.

2024-06-21 06:21 UTC, RanabirChakraborty commented
Thanks @rpelisse for the review, I have modified it accordingly. You can check the build in CCI `eap-6.4.x-build` 100

2024-06-21 07:10 UTC, rpelisse requested changes
@RanabirChakraborty still a blank line, but apart from that, looks goo to me.

@spyrkob any comments on your part?

2024-06-24 10:12 UTC, RanabirChakraborty commented
CCI testsuite job: eap-6.4.x-testsuite 15

2024-06-24 10:21 UTC, merged