Fix paths in perun files.
jboss-set/harmonia pull request #22
Opened 2020-08-26 09:59 UTC by baranowb

2020-08-26 10:06 UTC, rpelisse requested changes

2020-08-26 10:06 UTC, rpelisse commented on perun/perun.sh
> +SCRIPT=$(readlink -f "$0")
replace "$0" by "${0}" to respect best practices

2020-08-26 10:06 UTC, rpelisse commented on perun/perun.sh
> +readonly SCRIPT_FOLDER=$(dirname "$SCRIPT")
same here: "${SCRIPT}"

2020-08-26 10:06 UTC, rpelisse commented on perun/run-test.sh
> +bash -x ${SCRIPT_FOLDER}/${TEST_RUN_SCRIPT}
Add double quote, this will prevent inconsistent behavior if a space character somehow ends up in one of the variable:

"${SCRIPT_FOLDER}/${TEST_RUN_SCRIPT}"

2020-08-26 15:08 UTC, rpelisse requested changes

2020-08-26 15:08 UTC, rpelisse commented on perun/perun.sh
> +SCRIPT=$(readlink -f "${0}")
SCRIPT can be readonly too, right? Other than that, LGTM!

2020-08-27 08:47 UTC, rpelisse approved these changes

2020-08-27 08:48 UTC, rpelisse commented
@spyrkob can you review and if you don't find anything to change, rebase and merge?  Thanks!

2020-10-05 18:00 UTC, rpelisse commented
@baranowb is this PR still relevant? Should we look into approving it and merging it into master?

2020-10-09 06:16 UTC, baranowb commented
yeah.

2021-03-09 12:33 UTC, rpelisse commented
@baranowb any reason for this to not have been merged into master?

2021-03-09 13:34 UTC, merged