[SET-334] Change eap-job to work on CCI
jboss-set/harmonia pull request #26
Opened 2021-03-08 16:10 UTC by spyrkob

First part of 'harmonizing' CCI - scripts for build and testsuite jobs

2021-03-08 16:10 UTC, spyrkob commented
@rpelisse could you take a look when you have a moment?

2021-03-09 12:32 UTC, rpelisse requested changes

2021-03-09 12:32 UTC, rpelisse commented on eap-job.sh
>  readonly MAVEN_WAGON_HTTP_POOL=${WAGON_HTTP_POOL:-'false'}
That will work on CCI, but break Thunder. We probably should use something like:

if [ ${HOSTNAME} startsWith Thunder ]
   readonly MAVEN_SETTINGS_XML=${MAVEN_SETTINGS_XML-'/home/jboss/settings.xml'}
fi

(this is pseudo-code, not bash!)

2021-03-09 12:32 UTC, rpelisse commented on eap-job.sh
> +  zip -qr jboss-eap-src-${GIT_COMMIT:0:7}.zip ${EAP_SOURCES_FOLDER}
This also needs a if because it might take quite a lot of time on Thunder, for no good reason).

2021-03-09 12:32 UTC, rpelisse commented on eap-job.sh
> +  mvn clean install -Dts.skipTests=true "${FAIL_AT_THE_END}" ${MAVEN_SETTINGS_XML_OPTION} -B ${BUILD_OPTS} ${@}
This also requires a if because this building process is specific to CCI (thunder build with tests and then  run the testsuite, while CCI split)

2021-03-09 12:36 UTC, spyrkob commented on eap-job.sh
>  readonly MAVEN_WAGON_HTTP_POOL=${WAGON_HTTP_POOL:-'false'}
Yeah, that's gonna stay on cci branch for now, I was gonna talk to you about merging them into one branch once all of CCI scripts (or as much as possible)is here

2021-03-09 13:56 UTC, merged