[SET-334] Harmonia jobs for installer and UMB notifier
jboss-set/harmonia pull request #29
Opened 2021-03-17 16:18 UTC by spyrkob

JIRA: https://projects.engineering.redhat.com/browse/SET-334

2021-03-17 16:22 UTC, spyrkob commented
@rpelisse when you have a moment could you take a look at this PR? I'm sure there's a better way of doing a lot of this scripts ;)
For now this will only go into CCI branch, I'll worry about merging it with master after Olympus changes are done.

2021-04-16 15:04 UTC, rpelisse requested changes
@spyrkob it's pretty solid stuff. i've seen a couple of very minor things (and I think you should pass shellcheck on the scripts, if you have not), but apart from that, it seems pretty solid.

Can you set a pr against Olympus branch too?

Thanks!

2021-04-16 15:04 UTC, rpelisse commented on umb-build-message.sh
> +echo $msg | jq > message_body.json
"${msg}" ;)

2021-04-19 11:51 UTC, spyrkob commented on eap-installer.sh
> +if [ "${ACTION}" != 'testsuite' ] && [ "${ACTION}" != 'installer' ] &&
That would be a partial match though wouldn't it? So would match anything with those strings in like  "commons_build" or "not_installer"

2021-04-19 12:31 UTC, rpelisse commented on eap-installer.sh
> +if [ "${ACTION}" != 'testsuite' ] && [ "${ACTION}" != 'installer' ] &&
No you can make it "strict":
```
grep -e 'izpack'  | gre -e 'commons'  | grep -e 'testsuite'  | grep 'installer'
```

But honestly, it's not really much better, nor shorter, so you may forget about it :)

2021-04-27 12:17 UTC, merged