upgrade-components-report.sh - change logger URL, define $JAVA_HOME
jboss-set/harmonia pull request #30
Opened 2021-03-25 09:54 UTC by TomasHofman

2021-03-25 09:56 UTC, TomasHofman commented
@rpelisse would you review please?

2021-04-16 08:26 UTC, rpelisse requested changes
Can you also do a PR against the Olympus branch ?

2021-04-16 08:26 UTC, rpelisse commented on upgrade-components-report.sh
> +readonly JAVA_HOME=${JAVA_HOME:-'/opt/oracle/jdk1.8.0_181'}
I would not hard code a default for the JDK. It should defined by the caller, so I would just do:

```readonly JAVA_HOME=${JAVA_HOME}```

and add a test if no there already:
```
if [ -z "${JAVA_HOME} ]; then
  echo 'No JAVA_HOME defined - abort.'
  exit ...
if

if [ ! -d "{JAVA_HOME} ]; then
  echo "${JAVA_HOME is not a directory or does not exists.'
  exit ...
fi
```

2021-04-16 08:26 UTC, rpelisse commented on upgrade-components-report.sh
> +"$JAVA_HOME"/bin/java -Dlogger.projectCode="${LOGGER_PROJECT_CODE}" \
```"${JAVA_HOME}/bin/java"``` would be better IMHO

2021-04-16 08:51 UTC, TomasHofman commented on upgrade-components-report.sh
> +readonly JAVA_HOME=${JAVA_HOME:-'/opt/oracle/jdk1.8.0_181'}
@rpelisse now I'm thinking more about the Olympus situation - is the $JAVA_HOME var expected to be defined and visible to the Jenkins job by default? (I mean without the Jenkins job having to define it by itself.)

The reason why this var was added was purely to make sure that the script uses *the* JDK instance which had the RH cert installed (on thunder). Apart from this aspect, it doesn't matter which JDK instance is used, any instance will do. I just think that requiring each Jenkins job to define path to JAVA_HOME is unnecessary and adds noise. There is going to be maybe 6 to 10 jobs using this script, I would rather if this was not defined in each one.

IMO ideal situation (for Olympus) would be if there was a default system java installation (available in $PATH or in /usr/lib/jvm/java/bin or such), which would have RH cert installed, and then I don't have to care about its' location (in most jobs, unless I need something special, in which case I would override it).

2021-04-16 08:52 UTC, TomasHofman commented on upgrade-components-report.sh
> +"$JAVA_HOME"/bin/java -Dlogger.projectCode="${LOGGER_PROJECT_CODE}" \
Right, will fix.

2021-04-16 09:10 UTC, TomasHofman commented on upgrade-components-report.sh
> +readonly JAVA_HOME=${JAVA_HOME:-'/opt/oracle/jdk1.8.0_181'}
Olympus PR: https://github.com/jboss-set/harmonia/pull/34

It just leaves out the hard-coded logger URL. I think we don't really need to care about JAVA_HOME in the Olympus case. But let me know what you think.

2021-04-16 09:10 UTC, rpelisse commented on upgrade-components-report.sh
> +readonly JAVA_HOME=${JAVA_HOME:-'/opt/oracle/jdk1.8.0_181'}
This is fully automated on Olympus. You won't have to add the JAVA_HOME to each job, because each jobs will be generated.

2021-04-16 10:28 UTC, merged