Introduce VBE parts
jboss-set/harmonia pull request #75
Opened 2022-05-04 06:57 UTC by baranowb

2022-05-04 12:53 UTC, rpelisse commented on eap-job/base.sh
> +      export IS_MAVEN_LOCAL=true
Note: there is no "boolean" type in shell, so this is a string. I would suggest you used this syntax:

`IS_MAVEN_LOCAL='true'`

If this value is not changing, you should add the prefix readonly and allow it to be overriden by caller (this will come handy, no matter what):

`readonly IS_MAVEN_LOCAL=${IS_MAVEN_LOCAL:-'true'}`

2022-05-04 12:54 UTC, rpelisse commented on eap-job/base.sh
> +  	#copy, into local, if its dwn, dont copy, just alter
as the content of this if stmt is pretty long, I would suggest to turn it into a function, using the comment to name it:
```
copyIntoLocalUnlessItsAlreadyDownloaded()  {
....
}
```

2022-05-04 12:55 UTC, rpelisse commented on eap-job/base.sh
> +  	VBE_JAR="$(ls "${PARENT_JOB_DIR}"/target/*-extension-*[^sources].jar)"
You can remove the " around the $() which will also make it easier to read.

2022-05-04 12:56 UTC, rpelisse commented on eap-job/base.sh
> +	if [ -z ${IS_MAVEN_LOCAL} ]; then
Add " around the variable name, to avoid breaking the script is the var is empty or (somehow) has a space in it (the equivalent of NPE for Bash ;) )

2022-05-04 12:56 UTC, rpelisse commented on eap-job/base.sh
> +		cp -r $MAVEN_HOME/* "$(pwd)/maven"
"${MAVEN_HOME}"/*

2022-05-04 12:57 UTC, rpelisse commented on eap-job/base.sh
> +		export MAVEN_HOME="$(pwd)/maven"
```
readonly MAVEN_HOME="$(pwd)/maven"
export MAVEN_HOME
```

UNLESS the value is going to change of course.

2022-05-04 12:57 UTC, rpelisse commented on eap-job/base.sh
> +	mkdir -p $MAVEN_HOME/lib/ext
`"${MAVEN_HOME}/lib/ext"`

2022-05-04 12:58 UTC, rpelisse commented on eap-job/base.sh
> +	cp $VBE_JAR $MAVEN_HOME/lib/ext/
`cp "${VBE_JAR}" "${MAVEN_HOME}/lib/ext/"`

2022-05-04 12:58 UTC, rpelisse commented on eap-job/base.sh
> +            export MAVEN_OPTS="${MAVEN_OPTS} -Dvbe.channels=${VBE_CHANNELS}"
readonly to MAVEN_OPTS if applicable.

2022-05-04 12:59 UTC, rpelisse commented on eap-job/base.sh
> +  export PATH=${MAVEN_HOME}/bin:${PATH}
`export PATH="${MAVEN_HOME}/bin:${PATH}"`

2022-05-04 13:00 UTC, rpelisse commented on eap-job/base.sh
>    readonly MAVEN_BIN_DIR=${MAVEN_HOME}/bin
readonly MAVEN_BIN_DIR="${MAVEN_HOME}/bin"

2022-05-04 13:01 UTC, rpelisse requested changes
@baranowb You should use shellcheck to validate your script, it would have complains about 99% of the stuff I've pointed out!

2022-05-04 13:01 UTC, rpelisse commented
@spyrkob any extra comments on your side?

2022-05-06 08:21 UTC, spyrkob commented
> @spyrkob any extra comments on your side?
Looks good (apart from stuff you pointed out 😉  )

2022-05-09 07:05 UTC, baranowb commented on eap-job/base.sh
> -  export PATH=${MAVEN_BIN_DIR}:${PATH}
it was injected twice.

2022-05-09 07:32 UTC, baranowb commented
> @baranowb You should use shellcheck to validate your script, it would have complains about 99% of the stuff I've pointed out!

  readonly PARAMS=${@}
                  ^--^ SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.
                  
  :)

2022-05-09 08:02 UTC, rpelisse requested changes
@baranowb a few more syntax issue.

2022-05-09 08:02 UTC, rpelisse commented on eap-job/base.sh
> +configure_mvn_vbe_if_required(){
This function is quite long, I would put the second part (will all the checks and exports) into a separate function.

2022-05-09 08:02 UTC, rpelisse commented on eap-job/base.sh
> +		cp "$VBE_JAR" "$MAVEN_HOME"/lib/ext/
mkdir -p "$MAVEN_HOME"/lib/ext => mkdir -p "${MAVEN_HOME}/lib/ext"
cp "$VBE_JAR" "$MAVEN_HOME"/lib/ext/ => cp "${VBE_JAR}" "${MAVEN_HOME}/lib/ext/"

Also, as "$MAVEN_HOME}/lib/ext/ is used twice, it would be better to have a variable defined for it:
MAVEN_LIB_EXT="${MAVEN_HOME}/lib/ext/"
So that we don't have to change the value in two separate place, if we need to.

2022-05-09 08:02 UTC, rpelisse commented on eap-job/base.sh
> +		readonly MAVEN_HOME="$MAVEN_HOME"
readonly MAVEN_HOME="$MAVEN_HOME" => 		readonly MAVEN_HOME="${MAVEN_HOME}"

2022-05-12 09:48 UTC, merged